inherit_gem:
  retrieva-cop:
    - "config/rubocop.yml"
    # comment unless use rails cops
    - "config/rails.yml"
    # comment unless use rspec cops
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.6.3
  # comment unless use rails cops
  TargetRailsVersion: 5.1.6