name: RetrievaCop
on: [pull_request]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0.1
    - run: |
        gem install bundler
        bundle install
    - name: Run rubocop
      run: bundle exec rubocop